version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
      - "8443:443" 
    volumes:
    - ./certs:/etc/nginx/certs
    depends_on:
      - backend

  backend:
    build: ./backend
    env_file:
      - backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src/db:/app/src/db

